import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import theme from "@/theme/theme";
import { CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-foreground text-background min-h-screen flex flex-col">
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <Navbar />
          <main className="flex-1 w-full">{children}</main> <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
